#!/usr/bin/env bash

#
# Perform an install of all developer dependencies.
#

# TODO: Figure out how to list only user-installed homebrew packages and remove any that are not
#       present in osx/packages.txt
# TODO: Run OS X setup scripts
# TODO: Use a stow ignore list (https://www.gnu.org/software/stow/manual/html_node/Types-And-Syntax-Of-Ignore-Lists.html)
#       to add
# TODO: Test for each package manager before installing packages

set -o errexit
set -o nounset
set -o pipefail

#
# Check dependencies
#

if [[ -z "${GOPATH}" ]]; then
    echo "ERROR: Must set GOPATH before running this script."
    exit 1
fi

#
# Install dependencies
#

export HOMEBREW_NO_AUTO_UPDATE=1

brew update

while read -r tap; do
  brew tap "${tap}"
done < osx/taps.txt

while read -r package; do
  brew install "${package}"
done < osx/packages.txt

while read -r package; do
  brew cask install "${package}"
done < osx/casks.txt

for tap in $(echo "$(cat osx/taps.txt)" "$(cat osx/taps.txt)" "$(brew tap)" | tr ' ' '\n' | sort | uniq -u); do
  echo "Found extraneous tapped homebrew tap ${tap}; consider adding it to osx/taps.txt."
done

for package in $(echo "$(cat osx/casks.txt)" "$(cat osx/casks.txt)" "$(brew cask list)" | tr ' ' '\n' | sort | uniq -u); do
  echo "Found extraneous installed homebrew cask ${package}; consider adding it to osx/casks.txt."
done

# (Re)install nodenv hooks for any existing installed node versions
nodenv package-hooks install --all

#
# Change shell
#

if ! grep "/usr/local/bin/zsh" /etc/shells > /dev/null; then
    echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells > /dev/null
fi

if [[ "$(dscl . -read "${HOME}" UserShell | cut -d ' ' -f 2)" != "/usr/local/bin/zsh" ]]; then
  chsh -s /usr/local/bin/zsh
fi

#
# Link dotfiles
#

packages=(
    "ag"
    "bin"
    "clojure"
    "emacs"
    "git"
    "haskell"
    "javascript"
    "ruby"
    "ssh"
    "tmux"
    "vim"
    "zsh"
)

for pkg in "${packages[@]}"; do
    stow --target="$HOME" --verbose=1 "${pkg}"
done

#
# Install language packages
#

go_packages=(
    "github.com/alecthomas/gometalinter"
    "github.com/kardianos/govendor"
    "github.com/nsf/gocode"
    "golang.org/x/tools/cmd/gorename"
    "golang.org/x/tools/cmd/guru"
)

python_packages=(
    "tmuxp"
)

ruby_packages=(
    "pry"
    "terminal-notifier"
)

for pkg in "${go_packages[@]}"; do
    go get -u "${pkg}"
done

for pkg in "${node_packages[@]}"; do
    npm install -g "${pkg}"
done

for pkg in "${python_packages[@]}"; do
    pip install "${pkg}"
done

for pkg in "${ruby_packages[@]}"; do
    gem install "${pkg}"
done
