#!/usr/bin/env bash

#
# Install OS X-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

if [[ "${OSTYPE}" != darwin* ]]; then
  echo "ERROR: This script can only be run on macOS."
  exit 1
fi

CURRENT_SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"

if command -v port > /dev/null 2>&1; then
  "${CURRENT_SCRIPT_PATH}/macports/install"
elif command -v brew > /dev/null 2>&1; then
  "${CURRENT_SCRIPT_PATH}/homebrew/install"
fi

# tmuxp is not available through Homebrew/MacPorts
pip install tmuxp
