#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

PREVIOUS_HEAD="$1"
EMPTY_SHA="0000000000000000000000000000000000000000"

# On `git clone`
if [[ "${PREVIOUS_HEAD}" == "${EMPTY_SHA}" ]]; then
  # TODO(ndhoule): Template out git repository
  echo "TODO: Implement me" > /dev/null
fi
