#!/bin/bash

#
# Adds a reference to the Pivotal Story ID in the commit if contained in the branch name
# (e.g. my-great-feature-100000000)
#
# Based on: https://github.com/goodeggs/kale/commit/e378408d56bcf812cab56487a6eef1c09367f787
#

set -o errexit
set -o nounset
set -o pipefail

BRANCH=$(git symbolic-ref --short HEAD)
STORY_ID=$(echo "${BRANCH}" | grep -o '[-_]\#\?\d\+$' | sed -E "s/^-#?//") || echo ""

if [[ -n "${STORY_ID}" ]]; then
  ORIG_MSG_FILE="$1"
  ORIG_MSG=$(cat "$1")

  if [[ "${ORIG_MSG}" == *"{{pivotal_story_id}}"* ]]; then
    # Uncomment the Pivotal story link line; it's commented so that aborting the commit doesn't save
    # the Pivotal story template line as the commit title
    ORIG_MSG=$(sed '/{{pivotal_story_id}}/s/^# //g' <<< "${ORIG_MSG}")
    # Substitute the Pivotal story ID into the commit message
    ORIG_MSG=$(sed "/{{pivotal_story_id}}/s/{{pivotal_story_id}}/${STORY_ID}/g" <<< "${ORIG_MSG}")
    (echo "${ORIG_MSG}") > "$ORIG_MSG_FILE"
  fi
fi
