#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --if-not-exists tuple https://dl.tuple.app/repo/stable
flatpak remote-add --if-not-exists kdeapps https://distribute.kde.org/kdeapps.flatpakrepo

packages=(
	"flathub com.bitwarden.desktop"
	"flathub com.cassidyjames.butler"
	"flathub com.discordapp.Discord"
	"flathub com.github.iwalton3.jellyfin-media-player"
	"flathub com.github.tchx84.Flatseal"
	"flathub com.nextcloud.desktopclient.nextcloud"
	"flathub com.rawtherapee.RawTherapee"
	"flathub com.slack.Slack"
	"flathub com.spotify.Client"
	"flathub com.valvesoftware.Steam"
	"flathub io.github.TransmissionRemoteGtk"
	"flathub io.github.mimbrero.WhatsAppDesktop"
	"flathub io.github.seadve.Kooha"
	"flathub io.mpv.Mpv"
	"flathub org.chromium.Chromium"
	"flathub org.gimp.GIMP"
	"flathub org.gnome.Boxes"
	"flathub org.gnome.Calculator"
	"flathub org.gnome.DejaDup"
	"flathub org.gnome.FileRoller"
	"flathub org.gnome.FontManager"
	"flathub org.gnome.gedit"
	"flathub org.libreoffice.LibreOffice"
	"flathub org.mozilla.Thunderbird"
	"flathub org.musicbrainz.Picard"
	"flathub org.virt_manager.virt-viewer"
	"kdeapps org.kde.xwaylandvideobridge"
	"tuple app.tuple.app"
)

if ! command -v flatpak >/dev/null 2>&1; then
	echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
	exit 1
fi

for package in "${packages[@]}"; do
	# Split repository name / package name
	# shellcheck disable=SC2086
	flatpak install -y $package
done

flatpak permission-set flatpak background app.tuple.app yes
flatpak permission-set flatpak updates app.tuple.app yes

# Slack defaults to xwayland when an x11 socket is available
flatpak override --user --nosocket=x11 com.slack.Slack
# XXX(ndhoule): Hack around screensharing issue: https://github.com/flathub/com.slack.Slack/issues/101
sudo sed -i -e 's/"WebRTCPipeWireCapturer"/"LebRTCPipeWireCapturer"/' /var/lib/flatpak/app/com.slack.Slack/current/active/files/extra/resources/app.asar
