#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! command -v rpm-ostree > /dev/null 2>&1; then
  echo "ERROR: Could not find \`rpm-ostree\`. Exiting."
  exit 1
fi

# Install DejaVu Sans Mono Nerd Fonts
if [[ ! -d  "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font" ]]; then
  mkdir -p "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font"
  curl --fail --silent --show-error --location \
    "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Bold/DejaVuSansMNerdFont-Bold.ttf" \
    > "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font/DejaVuSansM_Nerd_Font_Bold.ttf"
  curl --fail --silent --show-error --location \
    "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Bold-Italic/DejaVuSansMNerdFont-BoldOblique.ttf" \
    > "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font/DejaVuSansM_Nerd_Font_Bold_Oblique.ttf"
  curl --fail --silent --show-error --location \
    "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Italic/DejaVuSansMNerdFont-Oblique.ttf" \
    > "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font/DejaVuSansM_Nerd_Font_Oblique.ttf"
  curl --fail --silent --show-error --location \
    "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/DejaVuSansMNerdFont-Regular.ttf" \
    > "${XDG_DATA_HOME}/fonts/Unknown Vendor/TrueType/DejaVuSansM Nerd Font/DejaVuSansM_Nerd_Font_Regular.ttf"
fi

if ! test -f /etc/yum.repos.d/hashicorp.repo; then
  curl --fail --silent --show-error --location https://rpm.releases.hashicorp.com/fedora/hashicorp.repo \
    | sudo tee /etc/yum.repos.d/hashicorp.repo > /dev/null 2>&1
fi

# https://packagecloud.io/filips/FirefoxPWA
if ! test -f /etc/yum.repos.d/firefoxpwa.repo; then
  sudo rpm --import https://packagecloud.io/filips/FirefoxPWA/gpgkey
  echo -e "[firefoxpwa]\nname=FirefoxPWA\nmetadata_expire=300\nbaseurl=https://packagecloud.io/filips/FirefoxPWA/rpm_any/rpm_any/\$basearch\ngpgkey=https://packagecloud.io/filips/FirefoxPWA/gpgkey\nrepo_gpgcheck=1\ngpgcheck=0\nenabled=1" \
    | sudo tee /etc/yum.repos.d/firefoxpwa.repo > /dev/null 2>&1
fi

# TODO:
# - aws-vault
# - bitwarden-cli
# - chromaprint-tools
# - lua-language-server
# - ngrok
# - veracrypt
packages=(
  ShellCheck
  alacritty
  ansible python3-ansible-lint
  aspell aspell-en
  awscli2
  certbot
  clang
  consul consul-template
  direnv
  emacs
  entr
  fd-find
  gammastep gammastep-indicator
  gh
  git-crypt
  gnome-system-monitor
  gvfs-afc gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb
  iperf3
  mpv
  neovim python3-neovim
  netcat
  nomad nomad-pack
  openssh-askpass
  parallel
  podman-docker
  ripgrep
  stow
  terraform terraform-ls
  the_silver_searcher
  tidy
  tmux python3-tmuxp
  traceroute
  virt-manager
  watchman
  wlogout
  wofi
  yubikey-manager
  zsh

  # Fonts
  fira-code-fonts
  google-roboto-fonts
  jetbrains-mono-fonts
  material-icons-fonts
  rsms-inter-fonts
)

rpm-ostree update

# shellcheck disable=SC2068
rpm-ostree install --idempotent ${packages[@]}
