#!/usr/bin/env bash

#
# Install dotfiles.
#
# Authors:
#   Nathan Houle <nathan@nathanhoule.com>
#

set -o nounset
set -o errexit

#
# Directories.
#

PWD=$(dirname $(greadlink -f $0))
DOTFILES_DIR=$(cd "${PWD}" && git rev-parse --show-toplevel)

#
# Load dependencies.
#

source "${DOTFILES_DIR}/.lib/utils.sh"

#
# Load all install scripts.
#

_install() {
  # Find all install scripts, excluding any in this directory
  find \
    -E \
    "${DOTFILES_DIR}" \
    -maxdepth 3 \
    -type f \
    -iregex '.*install(\..*)?' \
    -not -path "*/$(basename $PWD)/*" \
    -print0 | \
  while read -d $'\0' script; do
    # Use env to allow scripts to be written in any language
    log_debug "Loading ${script}..."
    env "${script}"
  done
}

#
# Init.
#

(_install)
