#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

CURRENT_SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

packages=(
  "flathub com.bitwarden.desktop"
  "flathub com.discordapp.Discord"
  "flathub com.github.alecaddd.sequeler"
  "flathub com.github.tchx84.Flatseal"
  "flathub com.slack.Slack"
  "flathub com.spotify.Client"
  "flathub com.transmissionbt.Transmission"
  "flathub com.yubico.yubioath"
  "flathub io.github.celluloid_player.Celluloid"
  "flathub org.darktable.Darktable"
  "flathub org.gnome.Calculator"
  "flathub org.gnome.FontManager"
  "flathub org.gnome.seahorse.Application"
  "flathub org.libreoffice.LibreOffice"
  # "flathub org.mozilla.firefox"
  "flathub org.signal.Signal"
  "flathub org.zealdocs.Zeal"
  "flathub io.github.mimbrero.WhatsAppDesktop"

)

if ! command -v flatpak > /dev/null 2>&1; then
  echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
  exit 1
fi

for package in "${packages[@]}"; do
  # Split repository name / package name
  # shellcheck disable=SC2086
  flatpak install -y $package
done

# Enable Wayland support in Firefox
flatpak override --user --socket=wayland --nosocket=x11 --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox

# Allow Zeal r/w access to dotfiles/packages/zeal
flatpak override --user --filesystem="$(realpath "${CURRENT_SCRIPT_PATH}/../../packages/zeal" | sed "s|${HOME}|~|"):rw" org.zealdocs.Zeal

# Enable Wayland support in Signal
flatpak override --user --socket=wayland --nosocket=x11 org.signal.Signal
tee "${HOME}/.local/share/applications/org.signal.Signal.desktop" << 'EOF' > /dev/null
[Desktop Entry]
Name=Signal
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=signal --file-forwarding org.signal.Signal --enable-features=UseOzonePlatform --ozone-platform=wayland @@u %U @@
Terminal=false
Type=Application
Icon=org.signal.Signal
StartupWMClass=Signal
Comment=Private messaging from your desktop
MimeType=x-scheme-handler/sgnl;x-scheme-handler/signalcaptcha;
Categories=Network;InstantMessaging;Chat;
X-Desktop-File-Install-Version=0.26
X-Flatpak-RenamedFrom=signal-desktop.desktop;
X-Flatpak=org.signal.Signal
EOF

# Enable Wayland support in Slack
flatpak override --user --socket=wayland --nosocket=x11 com.slack.Slack
tee "${HOME}/.local/share/applications/com.slack.Slack.desktop" << 'EOF' > /dev/null
[Desktop Entry]
Name=Slack
Comment=Slack Desktop
GenericName=Slack Client for Linux
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=slack --file-forwarding com.slack.Slack --enable-features=WebRTCPipeWireCapturer --enable-features=UseOzonePlatform --ozone-platform=wayland @@u %U @@
Icon=com.slack.Slack
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Network;InstantMessaging;
MimeType=x-scheme-handler/slack;
X-Desktop-File-Install-Version=0.26
StartupWMClass=Slack
X-Flatpak-RenamedFrom=slack.desktop;
X-Flatpak=com.slack.Slack
EOF
