#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

CURRENT_SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

packages=(
  "flathub com.bitwarden.desktop"
  #"flathub com.discordapp.Discord"
  "flathub com.github.alecaddd.sequeler"
  "flathub com.github.tchx84.Flatseal"
  "flathub com.slack.Slack"
  "flathub com.spotify.Client"
  "flathub org.mozilla.firefox"
  #"flathub com.transmissionbt.Transmission"
  "flathub com.yubico.yubioath"
  "flathub io.bit3.WhatsAppQT"
  "flathub io.github.celluloid_player.Celluloid"
  #"flathub org.darktable.Darktable"
  "flathub org.gnome.Calculator"
  "flathub org.gnome.FontManager"
  #"flathub org.gnome.Lollypop"
  #"flathub org.gnome.seahorse.Application"
  "flathub org.libreoffice.LibreOffice"
  "flathub org.signal.Signal"
  "flathub org.zealdocs.Zeal"
)

if ! command -v flatpak > /dev/null 2>&1; then
  echo "ERROR: Could not find \`flatpak\`. Please install yay and re-run this script."
  exit 1
fi

for package in "${packages[@]}"; do
  # Split repository name / package name
  # shellcheck disable=SC2086
  flatpak install -y $package
done

# Enable Wayland support in Firefox
flatpak override --user --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox

# Allow Zeal r/w access to dotfiles/packages/zeal
flatpak override --user --filesystem="$(realpath "$(dirname "${CURRENT_SCRIPT_PATH}")/../../packages/zeal" | sed "s|${HOME}|~|"):rw" org.zealdocs.Zeal
