#!/usr/bin/env bash

#
# Install Arch Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

CURRENT_SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"
DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

if [[ "${DISTRO_NAME}" != "Arch Linux" ]]; then
  echo "ERROR: This script can only be run on Arch Linux."
  exit 1
fi

"${CURRENT_SCRIPT_PATH}/packages"
"${CURRENT_SCRIPT_PATH}/flatpaks"

# Allow Podman to run as user process
sudo touch /etc/subuid /etc/subgid
sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 "${USER}"
podman system migrate
# Silence warning about Docker compatibility
sudo touch /etc/containers/nodocker

# Enable system services
systemctl enable --now avahi-daemon.service
systemctl enable --now bluetooth.service
systemctl enable --now cups.service
systemctl enable --now ipp-usb.service
systemctl enable --now nextdns.service
systemctl enable --now pcscd.service
systemctl enable --now systemd-oomd.service
systemctl enable --now systemd-timesyncd.service

# Enable user services
systemctl --user enable --now podman.service

# Enable USB automounting
sudo tee /etc/udev/rules.d/99-media-automount.rules << 'EOF' > /dev/null
ACTION=="add", SUBSYSTEMS=="usb", SUBSYSTEM=="block", ENV{ID_FS_USAGE}=="filesystem", \
  RUN{program}+="/usr/bin/systemd-mount --no-block --automount=yes --collect $devnode"
EOF

# Set system timezone to current geolocation when NetworkManager connects to a network
sudo tee /etc/NetworkManager/dispatcher.d/09-timezone << 'EOF' > /dev/null
#!/bin/sh
case "$2" in
    up)
        timedatectl set-timezone "$(curl --fail https://ipapi.co/timezone)"
    ;;
esac
EOF
sudo chmod +x /etc/NetworkManager/dispatcher.d/09-timezone

# Allow Gammastep access to geolocation data
sudo patch --forward --unified --reject-file - /etc/geoclue/geoclue.conf << EOF
--- /etc/geoclue/geoclue.conf	2021-07-20 22:52:16.353737827 -0700
+++ /etc/geoclue/geoclue.patch.conf	2021-07-20 22:52:52.626936247 -0700
@@ -128,3 +128,8 @@
 allowed=true
 system=false
 users=
+
+[gammastep]
+allowed=true
+system=false
+users=
EOF

# Enable mdns name resolution (e.g. .local)
sudo patch --forward --unified --reject-file - /etc/nsswitch.conf << EOF
--- nsswitch.conf       2021-12-06 18:41:28.000000000 -0800
+++ nsswitch.patch.conf 2022-06-11 11:32:09.016976489 -0700
@@ -8,7 +8,7 @@

 publickey: files

-hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
+hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns
 networks: files

 protocols: files
EOF

"${CURRENT_SCRIPT_PATH}/setup-greetd"

if [[ -x "${CURRENT_SCRIPT_PATH}/by_hostname/${HOSTNAME}" ]]; then
  "${CURRENT_SCRIPT_PATH}/by_hostname/${HOSTNAME}"
fi
