#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! command -v yay > /dev/null 2>&1; then
  echo "ERROR: Could not find \`yay\`. Please install yay and re-run this script."
  exit 1
fi

packages=(
  #
  # Base System
  #

  acpi
  base
  base-devel
  btrfs-progs
  efibootmgr
  linux linux-headers
  linux-firmware
  linux-lts linux-lts-headers
  mesa libva-mesa-driver
  corectrl mesa-demos util-linux vulkan-tools

  #
  # System Utilities
  #

  aspell
  exfatprogs

  #
  # Package Management
  #

  flatpak
  reflector

  #
  # Printing
  #

  cups

  #
  # Audio
  #

  pavucontrol
  pipewire wireplumber pipewire-alsa pipewire-pulse libpipewire02
  playerctl
  pamixer

  #
  # Bluetooth
  #

  blueman
  bluez
  bluez-utils

  #
  # Display manager
  #

  greetd greetd-wlgreet

  #
  # Networking
  #

  networkmanager nm-connection-editor

  #
  # Desktop environment
  #

  imv
  flashfocus-git
  geoclue
  gnome-system-monitor
  thunar tumbler thunar-dropbox
  gvfs gvfs-mtp gvfs-gphoto2 gvfs-afc gvfs-smb

  #
  # Wayland
  #

  gammastep
  grim grimshot slurp wf-recorder
  qt5-wayland qt6-wayland
  wayland
  wev
  wl-clipboard
  xdg-user-dirs
  xorg-server-xwayland

  #
  # Wayland screen sharing
  #

  xdg-desktop-portal
  xdg-desktop-portal-gtk
  xdg-desktop-portal-wlr

  #
  # sway WM
  #

  light
  sway
  swaybg
  swayidle
  swaylock
  waybar python-gobject gtk3
  wlogout
  wob
  wofi

  #
  # Desktop apps
  #

  alacritty
  chromium
  dropbox
  veracrypt

  #
  # CLI apps
  #

  bitwarden-cli-bin

  #
  # YubiKey Support
  #

  yubikey-manager
  pcsc-tools

  #
  # Developer tools
  #

  android-tools android-udev
  asdf-vm
  aws-cli
  aws-vault
  certbot
  direnv-bin
  dnsutils
  podman-docker
  podman-dnsname
  docker-compose
  emacs
  fzf
  git git-crypt
  gnupg
  go
  github-cli
  jq
  lsof
  man-db
  mongodb-tools-bin
  neovim python-pynvim neovim-symlinks
  ngrok
  openssh
  parallel
  pass
  python python-pip
  ripgrep
  rsync
  stow
  sysstat
  terraform
  nomad
  consul consul-template
  vault
  the_silver_searcher
  time
  tmux
  tmuxp
  traceroute
  tree
  virtualbox virtualbox-guest-utils
  watchman-bin
  wget
  zip
  zsh

  #
  ## Linters
  #

  bashate
  luacheck
  shellcheck
  stylua-bin
  tidy

  #
  ## LSP Servers
  #

  lua-language-server-git
  terraform-ls-bin

  #
  # Fonts
  #

  ttf-dejavu-nerd
  noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
  otf-raleway
  ttf-dejavu
  ttf-mac-fonts
  ttf-material-design-icons-git
  ttf-ms-fonts
  ttf-roboto

  # TODO(ndhoule): SORT ME
  vorbis-tools
  mpv
  circleci-cli-bin
  inetutils
  blueberry # bluetooth
  xdg-desktop-portal-gtk gnome-settings-daemon
  jmtpfs
  gpxsee
  gpsbabel
  unzip
  dunst
  dasht
  websocat
  gnu-netcat
  entr
  usbutils
  system-config-printer
  google-messages
  sops
  avahi
  nss-mdns
  google-cloud-sdk
  libfido2
  cloud-sql-proxy-bin
  reflector
  simple-scan sane brscan5
  ansible ansible-lint
  chromaprint
  ethtool
  iperf3
  netcat
  nfs-utils
  packer
  picard
  putty
  screen
  speedtest-cli
  virt-manager
  wireguard-tools
  zsa-wally
)

# shellcheck disable=SC2068
yay -S --needed ${packages[@]}
