#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! command -v yay > /dev/null 2>&1; then
  echo "ERROR: Could not find \`yay\`. Please install yay and re-run this script."
  exit 1
fi

packages=(
  #
  # Base System
  #

  base
  base-devel
  btrfs-progs
  efibootmgr
  linux linux-headers
  linux-firmware
  linux-lts linux-lts-headers
  mesa libva-mesa-driver
  corectrl mesa-demos util-linux vulkan-tools
  earlyoom

  #
  # System Utilities
  #

  aspell
  exfatprogs

  #
  # Package Management
  #

  flatpak

  #
  # Printing
  #

  cups
  brother-hll2300d

  #
  # Audio
  #

  pavucontrol
  pipewire pipewire-alsa pipewire-pulse libpipewire02
  playerctl
  pamixer

  #
  # Bluetooth
  #

  bluez
  bluez-utils

  #
  # Display manager
  #

  greetd greetd-wlgreet

  #
  # Networking
  #

  nextdns

  #
  # Desktop environment
  #

  #adwaita-qt adwaita-qt4
  imv
  flashfocus-git
  #geoclue
  #gnome-keyring libsecret
  gnome-system-monitor
  nautilus nautilus-dropbox gvfs gvfs-mtp gvfs-gphoto2 gvfs-afc gvfs-smb

  #
  # Wayland
  #

  gammastep
  grim grimshot slurp wf-recorder
  qt5-wayland qt6-wayland
  wayland
  wl-clipboard
  xdg-user-dirs
  xorg-server-xwayland
  wev

  #
  # Wayland screen sharing
  #

  xdg-desktop-portal
  xdg-desktop-portal-wlr

  #
  # sway WM
  #

  sway
  swaybg
  swayidle
  swaylock
  waybar python-gobject gtk3
  wlogout
  wob
  wofi

  #
  # Desktop apps
  #

  #aftershotpro3
  alacritty
  chromium
  dropbox
  firefox
  #ice-ssb
  veracrypt

  #
  # CLI apps
  #

  bitwarden-cli-bin

  #
  # YubiKey Support
  #

  yubikey-manager
  pcsc-tools

  #
  # Developer tools
  #

  android-tools android-udev
  asdf-vm
  aws-cli
  aws-vault
  certbot
  direnv-bin
  dnsutils
  docker
  docker-compose
  emacs
  fzf
  git git-crypt
  gnupg
  go
  hub-bin
  jq
  lsof
  man-db
  mongodb-tools-bin
  neovim python-pynvim neovim-symlinks
  ngrok
  openssh
  parallel
  pass
  python python-pip
  ripgrep
  rsync
  stow
  sysstat
  terraform
  the_silver_searcher
  time
  tmux
  tmuxp
  traceroute
  tree
  virtualbox virtualbox-guest-utils
  watchman
  wget
  zip
  zsh

  #
  ## Linters
  #

  bashate
  shellcheck
  tidy

  #
  ## LSP Servers
  #

  lua-language-server-git
  terraform-ls-bin

  #
  # Fonts
  #

  nerd-fonts-dejavu-complete
  noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra
  otf-raleway
  ttf-dejavu
  ttf-mac-fonts
  ttf-material-design-icons-git
  ttf-roboto

  # TODO(ndhoule): SORT ME
  vorbis-tools
  brightnessctl
  mpv
  circleci-cli-bin
  inetutils
  blueberry # bluetooth
  xdg-desktop-portal-gtk gnome-settings-daemon
  task taskwarrior-tui
  jmtpfs
  gpxsee
  gpsbabel
  unzip
  dunst
  dasht
)

# Split array elements into individual package names
# shellcheck disable=SC2068
yay -S --needed ${packages[@]}
