#!/usr/bin/env bash

#
# Install dependencies via Homebrew.
#

set -o errexit
set -o nounset
set -o pipefail

if [[ "${OSTYPE}" != darwin* ]]; then
  echo "ERROR: This script can only be run on macOS."
  exit 1
fi

CURRENT_SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"

CASKS_LIST="${CURRENT_SCRIPT_PATH}/casks.txt"
PACKAGES_LIST="${CURRENT_SCRIPT_PATH}/packages.txt"
TAPS_LIST="${CURRENT_SCRIPT_PATH}/taps.txt"

if ! command -v brew > /dev/null 2>&1; then
  echo "ERROR: Could not find brew. Please install Homebrew and re-run this script."
  exit 1
fi

brew update

while read -r tap; do
  # Skip comments and empty lines
  if [[ -z "${pkg}" || "${pkg}" =~ ^# ]]; then
    continue
  fi

  HOMEBREW_NO_AUTO_UPDATE=1 brew tap "${tap}"
done < "${TAPS_LIST}"

while read -r pkg; do
  # Skip comments and empty lines
  if [[ -z "${pkg}" || "${pkg}" =~ ^# ]]; then
    continue
  fi

  # Lines may contain multiple packages, so don't double quote
  # shellcheck disable=SC2086
  HOMEBREW_NO_AUTO_UPDATE=1 brew install "${pkg}"
done < "${PACKAGES_LIST}"

while read -r pkg; do
  # Skip comments and empty lines
  if [[ -z "${pkg}" || "${pkg}" =~ ^# ]]; then
    continue
  fi

  # Lines may contain multiple packages, so don't double quote
  # shellcheck disable=SC2086
  HOMEBREW_NO_AUTO_UPDATE=1 brew cask install $pkg
done < "${CASKS_LIST}"
