#!/usr/bin/env ruby

require 'find'

CWD = File.expand_path(File.dirname(__FILE__))
DOTFILES_SRC = File.expand_path(File.join(CWD, '..'))
BASE_DEPTH = DOTFILES_SRC.split('/').length

# Scan each subdirectory for an install.* script and run it if it exists
Find.find(DOTFILES_SRC) do |path|
  # Don't search dot folders, max depth of two, and skip this `install` folder
  if File.basename(path)[0] == '.' or path.split('/').length - BASE_DEPTH > 3 or path == CWD or path =~ /#?.*[#~]/
      Find.prune
  end

  if path =~ /^.*\/install.*/
    puts "Running installation script #{path.split(DOTFILES_SRC)[1][1..-1]}..."
    system("/usr/bin/env #{path}")
  end
end
