#
# Brewfile
#
# Run this file by executing `brew bundle Brewfile`.
#

#
# Prep
#

update
upgrade


#
# Packages
#

install ack
install android-sdk
install autoconf
install automake
install ccache
install closure-compiler
install cmake
install ctags
install curl
install emacs --cocoa --srgb
install git
install homebrew/completions/vagrant-completion
install hub
install mongodb
install ngrok
install openssl
install phantomjs
install postgresql
install reattach-to-user-namespace
install redis
install sqlite
install ssh-copy-id
install tidy
install tmux
install wget
install zsh

# Install GNU replacements for BSD utils
tap homebrew/dupes
install coreutils
install findutils
install gawk
install gnu-getopt
install gnu-indent
install gnu-sed
install gnu-tar
install gnutls
install grep
install readline

# FUSE
install osxfuse
install sshfs

# Clang
install cppcheck
install valgrind

# Python
install pyenv
install pyenv-ccache
install pyenv-pip-rehash
install pyenv-virtualenv

# Ruby
install rbenv
install rbenv-ctags
# TODO: Create a ~/.rbenv/default-gems file and put `bundler, pry` etc in it
install rbenv-default-gems
install rbenv-gem-rehash
install ruby-build

# YouCompleteMe requires Vim be built against latest Python binaries; install
# Python first
install python
unlink python
install macvim --override-system-vim

#
# Cleanup
#

linkapps
cleanup
