#!/usr/bin/env bash

#
# Install Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

CURRENT_SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

if [[ "${OSTYPE}" != linux* ]]; then
  echo "ERROR: This script can only be run on Linux."
  exit 1
fi

DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

case "${DISTRO_NAME}" in
  "Arch Linux")
    :
    "${CURRENT_SCRIPT_PATH}/arch/install"
    ;;
  *)
    :
    echo "Linux distribution '${DISTRO_NAME}' not supported."
    ;;
esac
