#!/usr/bin/env bash

#
# Install Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

CURRENT_SCRIPT_PATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

if [[ "${OSTYPE}" != linux* ]]; then
  echo "ERROR: This script can only be run on Linux."
  exit 1
fi

DISTRO_ID=$(cat /etc/*-release | grep "^ID=" | cut -d "=" -f 2)

# Create standard XDG base directories; if these don't exist, stow will create them as symlinks into
# the first package that asks for them (e.g. `packages/asdf/.config/asdf` will be linked as
# `${HOME}/.config` rather than "${HOME}/.config/asdf" as we want)
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${XDG_DATA_HOME}"

case "${DISTRO_ID}" in
  "arch")
    :
    "${CURRENT_SCRIPT_PATH}/arch/install"
    ;;
  "fedora")
    :
    "${CURRENT_SCRIPT_PATH}/fedora-silverblue/install"
    ;;
  *)
    :
    echo "Linux distribution '${DISTRO_ID}' not supported."
    ;;
esac
