#!/usr/bin/env bash

#
# Install Arch Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

if [[ "${DISTRO_NAME}" != "Arch Linux" ]]; then
  echo "ERROR: This script can only be run on Arch Linux."
  exit 1
fi

packages=(
  amd-ucode
  vulkan-radeon
)

# Split array elements into individual package names
# shellcheck disable=SC2086
yay -S --needed ${packages[0]}

# Enable system services
systemctl enable --now systemd-networkd.service
systemctl enable --now systemd-resolved.service

# Configure wired networking
sudo tee /etc/systemd/network/20-wired.network << 'EOF' > /dev/null
[Match]
Name=enp12s0

[Network]
DHCP=yes
IgnoreCarrierLoss=true
EOF
