#!/usr/bin/env bash

#
# Install Arch Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

if [[ "${DISTRO_NAME}" != "Arch Linux" ]]; then
  echo "ERROR: This script can only be run on Arch Linux."
  exit 1
fi

sudo tee /etc/systemd/network/00-wired.network << 'EOF' > /dev/null
[Match]
Name=enp5s0

[Network]
DHCP=yes
EOF

systemctl enable --now systemd-networkd.service
systemctl enable --now systemd-resolved.service

packages=(
  amd-ucode
  vulkan-radeon
)

# shellcheck disable=SC2068
yay -S --needed ${packages[@]}
