#!/usr/bin/env bash

#
# Install Arch Linux-specific dependencies.
#

set -o errexit
set -o nounset
set -o pipefail

DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

if [[ "${DISTRO_NAME}" != "Arch Linux" ]]; then
  echo "ERROR: This script can only be run on Arch Linux."
  exit 1
fi

packages=(
  amd-ucode
  vulkan-radeon
)

# shellcheck disable=SC2068
yay -S --needed ${packages[@]}
