#!/usr/bin/env bash

#
# Install Arch Linux-specific dependencies.
#
# https://wiki.archlinux.org/title/Dell_XPS_13_(9310)
#

set -o errexit
set -o nounset
set -o pipefail

DISTRO_NAME=$(hostnamectl | grep "Operating System" | cut -d ':' -f 2 | xargs)

if [[ "${DISTRO_NAME}" != "Arch Linux" ]]; then
  echo "ERROR: This script can only be run on Arch Linux."
  exit 1
fi

if [[ "${HOSTNAME}" != "endor" ]]; then
  echo "ERROR: This script can only be run on machines with the hostname 'endor'."
  exit 1
fi

packages=(
  brightnessctl
  iio-sensor-proxy
  intel-ucode
  sof-firmware
)

# shellcheck disable=SC2068
yay -S --needed ${packages[@]}
